services:
  filebrowser:
    image: filebrowser/filebrowser:v2-s6
    container_name: filebrowser
    restart: unless-stopped

    ports:
      - "8088:80"

    environment:
      PUID: 1000
      PGID: 1000

    volumes:
      # Istniejący wolumen, do którego chcesz wgrywać pliki
      - a3_missions:/srv/misje
      - arma3_armada_config:/srv/config
      - a3_preset:/preset/preset
      # Konfiguracja i baza użytkowników File Browser
      - filebrowser_database:/database
      - filebrowser_config:/config

volumes:
  a3_preset:
    name: a3_preset
  a3_missions:
    external: true
  arma3_armada_config:
    external: true

  filebrowser_database:
    name: filebrowser_database
  filebrowser_config:
    name: filebrowser_config
