services:
  rsync-ssh-server:
    image: a3-rsync-ssh-server:latest

    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - a3-rsync-ssh-server:latest

    pull_policy: build

    container_name: rsync-ssh-server
    restart: "no"

    environment:
      AUTO_STOP_AFTER_SECONDS: "1200"

    ports:
      - "8873:8873"

    volumes:
      # Klucze SSH
      # TODO: dodać bezpieczne rozwiązanie do automatycznego dodawania authorized_keys
      - /home/debian/klucze:/root/.ssh:ro

      # Konfiguracja
      - arma3_armada_config:/data/armada/config
      - arma3_phantom_venom_config:/data/phantom_venom/config
      - arma3_spartan_config:/data/spartan/config
      - arma3_rc_config:/data/armarc/config

      # WSPOLNE
      - a3_missions:/data/mpmissions

      # === DLC ===
      - a3_addons:/arma3/server/addons
      - a3_argo:/arma3/server/argo
      - a3_enoch:/arma3/server/enoch
      - a3_expansion:/arma3/server/expansion
      - a3_heli:/arma3/server/heli
      - a3_jets:/arma3/server/jets
      - a3_orange:/arma3/server/orange
