services:
  rsync-ssh-server:
    build:
      context: .
      dockerfile: Dockerfile

    image: a3-rsync-ssh-server:latest
    pull_policy: build

    container_name: rsync-ssh-server
    restart: unless-stopped
    ports:
      - "8873:8873"
    volumes:
      # Klucze SSH
      - /home/debian/klucze:/root/.ssh
      # Konfiguracja
      - arma3_armada_config:/data/armada/config
      - arma3_phantom_venom_config:/data/phantom_venom/config
      - arma3_spartan_config:/data/spartan/config
      - arma3_rc_config:/data/armarc/config
      #
      # autodownload Sceniaruszy
      - a3_scenario_dl:/data/scenario
      - a3_modlist:/data/modlist

      # WSPOLNE
      - a3_missions:/data/mpmissions
      - a3_mods:/data/mods

      # === DLC ===
      - a3_addons:/arma3/server/addons
      - a3_argo:/arma3/server/argo
      - a3_enoch:/arma3/server/enoch
      - a3_expansion:/arma3/server/expansion
      - a3_heli:/arma3/server/heli
      - a3_jets:/arma3/server/jets
      - a3_orange:/arma3/server/orange

      # LISTA MODÓW
      - "3den_enchanced:/arma3/mods/@3den enhanced"
      - "a3_thermal_impro:/arma3/mods/@a3 thermal improvement"
      - "ace:/arma3/mods/@ace"
      - "ace_armor_adjuster:/arma3/mods/@ace armor adjuster"
      - "ace_ars_ext_core:/arma3/mods/@ace3 arsenal extended - core"
      - "ace_ars_ext_rhs:/arma3/mods/@ace3 arsenal extended - rhs all-in-one"
      - "ace_ars_ext_vanil:/arma3/mods/@ace3 arsenal extended - vanilla (and ace)"
      - "acre2:/arma3/mods/@acre2"
      - "backpackonchest:/arma3/mods/@backpackonchest - redux"
      - "betterinventory:/arma3/mods/@better inventory"
      - "bettir_nvg:/arma3/mods/@bettir nvg"
      - "blastcore:/arma3/mods/@blastcore edited (standalone version)"
      - "bw_mod:/arma3/mods/@bwmod"
      - "cba_a3:/arma3/mods/@cba_a3"
      - "ch_view_distance:/arma3/mods/@ch view distance"
      - "chemical_warfare_plus:/arma3/mods/@chemical warfare plus"
      - "colombia:/arma3/mods/@umb colombia"
      - "ctab_devastator:/arma3/mods/@ctab devastator edition"
      - "cup_terrains_cwa:/arma3/mods/@cup terrains - cwa"
      - "cup_terrains_map:/arma3/mods/@cup terrains - maps"
      - "cup_terrians_core:/arma3/mods/@cup terrains - core"
      - "dco_soldier:/arma3/mods/@dco soldier fsm"
      - "dco_unit_scanner:/arma3/mods/@dco unitscanner"
      - "dui_sqd_radar:/arma3/mods/@dui - squad radar"
      - "enchenced_movment:/arma3/mods/@enhanced movement"
      - "enchenced_movment_rework:/arma3/mods/@enhanced movement rework"
      - "fir_aws:/arma3/mods/@fir aws(airweaponsystem)"
      - "fir_f16:/arma3/mods/@f-16 fighting falcon"
      - "fire_support:/arma3/mods/@fire support plus"
      - "grad_civ:/arma3/mods/@grad civilians"
      - "gruppe_adler_trenches:/arma3/mods/@gruppe adler trenches"
      - "immerse:/arma3/mods/@immerse"
      - "katmed:/arma3/mods/@kat - advanced medical"
      - "kt_weapon_pack:/arma3/mods/@kt weapon pack"
      - "kunduz_river_map:/arma3/mods/@kunduz river"
      - "ladder_tweak_remaster:/arma3/mods/@ladder tweak remastered"
      - "maptools:/arma3/mods/@maptools remastered"
      - "mrb_air:/arma3/mods/@mrb air visibility"
      - "mrb_sea:/arma3/mods/@mrb sea vessel visibility"
      - "mrb_vechicle:/arma3/mods/@mrb vehicle visibility"
      - "project_opfor:/arma3/mods/@project opfor"
      - "real_engine_enhanced:/arma3/mods/@real engine enhanced"
      - "rhsafrf:/arma3/mods/@rhsafrf"
      - "rhsgref:/arma3/mods/@rhsgref"
      - "rhsusaf:/arma3/mods/@rhsusaf"
      - "sahatra:/arma3/mods/@sa'hatra"
      - "virolahti_map:/arma3/mods/@virolahti - valtatie 7"
      - "vsm_all_in_ace:/arma3/mods/@ace3 arsenal extended - vsm all-in-one (fixed)"
      - "vsm_all_in_one:/arma3/mods/@vsm all-in-one collection"
      - "zeic:/arma3/mods/@zeic - zeus and eden interior community version"
      - "zeus_additions:/arma3/mods/@zeus additions"
      - "zeus_enchanced:/arma3/mods/@zeus enhanced"
      - "chernorus_map:/arma3/mods/@chernarus"

volumes:
  arma3_armada_config:
    name: arma3_armada_config
  arma3_phantom_venom_config:
    name: arma3_phantom_venom_config
  arma3_spartan_config:
    name: arma3_spartan_config
  arma3_rc_config:
    name: arma3_rc_config

  a3_scenario_dl:
    name: a3_scenario_dl
  a3_modlist:
    name: a3_modlist

  a3_missions:
    name: a3_missions

  a3_mods:
    name: a3_mods

  a3_addons:
    name: a3_addons

  a3_argo:
    name: a3_argo

  a3_enoch:
    name: a3_enoch

  a3_expansion:
    name: a3_expansion

  a3_heli:
    name: a3_heli

  a3_jets:
    name: a3_jets

  a3_orange:
    name: a3_orange

  # === MODY ===

  3den_enchanced:
    name: 3den_enchanced

  a3_thermal_impro:
    name: a3_thermal_impro

  ace:
    name: ace

  ace_armor_adjuster:
    name: ace_armor_adjuster

  ace_ars_ext_core:
    name: ace_ars_ext_core

  ace_ars_ext_rhs:
    name: ace_ars_ext_rhs

  ace_ars_ext_vanil:
    name: ace_ars_ext_vanil

  acre2:
    name: acre2

  backpackonchest:
    name: backpackonchest

  betterinventory:
    name: betterinventory

  bettir_nvg:
    name: bettir_nvg

  blastcore:
    name: blastcore

  bw_mod:
    name: bw_mod

  cba_a3:
    name: cba_a3

  ch_view_distance:
    name: ch_view_distance

  chemical_warfare_plus:
    name: chemical_warfare_plus

  colombia:
    name: colombia

  ctab_devastator:
    name: ctab_devastator

  cup_terrains_cwa:
    name: cup_terrains_cwa

  cup_terrains_map:
    name: cup_terrains_map

  cup_terrians_core:
    name: cup_terrians_core

  dco_soldier:
    name: dco_soldier

  dco_unit_scanner:
    name: dco_unit_scanner

  dui_sqd_radar:
    name: dui_sqd_radar

  enchenced_movment:
    name: enchenced_movment

  enchenced_movment_rework:
    name: enchenced_movment_rework

  fir_aws:
    name: fir_aws

  fir_f16:
    name: fir_f16

  fire_support:
    name: fire_support

  grad_civ:
    name: grad_civ

  gruppe_adler_trenches:
    name: gruppe_adler_trenches

  immerse:
    name: immerse

  katmed:
    name: katmed

  kt_weapon_pack:
    name: kt_weapon_pack

  kunduz_river_map:
    name: kunduz_river_map

  ladder_tweak_remaster:
    name: ladder_tweak_remaster

  maptools:
    name: maptools

  mrb_air:
    name: mrb_air

  mrb_sea:
    name: mrb_sea

  mrb_vechicle:
    name: mrb_vechicle

  project_opfor:
    name: project_opfor

  real_engine_enhanced:
    name: real_engine_enhanced

  rhsafrf:
    name: rhsafrf

  rhsgref:
    name: rhsgref

  rhsusaf:
    name: rhsusaf

  sahatra:
    name: sahatra

  virolahti_map:
    name: virolahti_map

  vsm_all_in_ace:
    name: vsm_all_in_ace

  vsm_all_in_one:
    name: vsm_all_in_one

  zeic:
    name: zeic

  zeus_additions:
    name: zeus_additions

  zeus_enchanced:
    name: zeus_enchanced

  chernorus_map:
    name: chernorus_map
