name: Release HTML Files

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Zmień na odpowiednią wersję Pythona
      - name: Process HTML files
        run: python scripts/process_html.py
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ env.VERSION }}
          files: release_files.txt
          draft: false
          prerelease: false
