name: Release HTML Files

on:
  push:
    tags:
      - "v*"  # Odpala workflow na tagach zaczynających się od "v"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Pobranie numeru wersji z taga
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Edytowanie plików HTML
        run: |
          VERSION=${{ env.VERSION }}
          FILES=()
          for file in VT_*_.html; do
            if [ -f "$file" ]; then
              BASENAME=$(basename "$file" .html)
              NEW_FILE="${BASENAME}_v${VERSION}.html"
              sed -i "s|<meta name=\"arma:PresetName\" content=\"[^\"]*\"|<meta name=\"arma:PresetName\" content=\"${BASENAME}_${VERSION}\"|g" "$file"
              sed -i "s|<h1>Arma 3 - Preset <strong>[^<]*</strong></h1>|<h1>Arma 3 - Preset <strong>${BASENAME}_${VERSION}</strong></h1>|g" "$file"
              mv "$file" "$NEW_FILE"
              FILES+=("$NEW_FILE")
            fi
          done
          echo "FILES=${FILES[@]}" >> $GITHUB_ENV

      - name: Utworzenie Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ env.VERSION }}
          files: ${{ env.FILES }}
          draft: false
          prerelease: false
