name: Release HTML Files

on:
  push:
    tags:
      - "v*"


jobs:
  build:
    name: Build Presets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout GITHUB code
      - name: Pobranie numeru wersji z taga
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - run: scripts/process_presets.sh .
        name: process HTML
      - run: ls tmp/
        name: List Files
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload ARMADA to Release
        uses: SierraSoftworks/gh-releases@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: 'true'
          files: "*.html"
