name: Release HTML Files

on:
  push:
    tags:
      - "v*"  # Odpala workflow na tagach zaczynających się od "v"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Pobranie numeru wersji z taga
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Edytowanie plików HTML
        run: |
          # TODO
          # nie dodaje nazwy pliku do content
          # trzeba jeszcze poprawić tytuł jakiś H1 czy coś 
          VERSION=${{ env.VERSION }}
          for file in VT_ARMADA_*.html VT_PHANTOM_*.html VT_SPARTAN_*.html; do
            if [ -f "$file" ]; then
              BASENAME=$(basename "$file" .html)
              sed -i "s|<meta name=\"arma:PresetName\" content=\"[^\"]*\"|<meta name=\"arma:PresetName\" content=\"$BASENAME_$VERSION\"|g" "$file"
            fi
          done

      - name: Utworzenie Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ env.VERSION }}
          files: |
            # TODO
            # nie wprowadza nazw wersji, nadal dodaje sourcecode
            VT_ARMADA_*.html
            VT_Phantom_*.html
            VT_SPARTAN_*.html
          draft: false
          prerelease: false
