name: Release HTML Files

on:
  push:
    tags:
      - "v*"


jobs:
  build:
    name: Build Presets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout GITHUB code
      - name: Pobranie numeru wersji z taga
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - run: scripts/process_presets.sh .
        name: process HTML
      - run: ls tmp/
        name: List Files
      - name: upload ARMADA
        uses: actions/upload-artifact@v4
        with:
          path: tmp/VT_ARMADA*.html
          if-no-files-found: error
          compression-level: 0
      - name: upload PHANTOM
        uses: actions/upload-artifact@v4
        with:
          path: tmp/VT_PHANTOM*.html
          if-no-files-found: error
          compression-level: 0
      - name: upload SPARTAN
        uses: actions/upload-artifact@v4
        with:
          path: tmp/VT_SPARTAN*.html
          if-no-files-found: error
          compression-level: 0
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload ARMADA to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: tmp/VT_ARMADA*.html
          asset_name: VT_ARMADA.html
          asset_content_type: text/html
      - name: Upload PHANTOM to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: tmp/VT_PHANTOM*.html
          asset_name: VT_PHANTOM.html
          asset_content_type: text/html
      - name: Upload SPARTAN to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: tmp/VT_SPARTAN*.html
          asset_name: VT_SPARTAN.html
          asset_content_type: text/html
