name: Release HTML Files

permissions:
  contents: write 
  releases: write 

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Process HTML files
        run: python scripts/process_html.py
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ env.VERSION }}
          body: |
            **Changes:**
            - ...
          files: scripts/release_files.txt  # Check if this is the correct path
          draft: false
          prerelease: false
